# -*- coding: utf-8 -*-
"""Aula de Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3ka74NTuyATq4gdypcIMzLdR2-ni8z0
"""

nome = "Michael"
print(nome)

nome = "Joacy"
nome

idade = 25
idade

idade + 3

def mais_um_ano(idade):
  return idade + 1

mais_um_ano(25)

filme1 = "Filme1"
filme2 = "Filme2"
filme3 = "Filme3"

filmes = ["Filme1", "Filme2", "Filme3"]
filmes

def imprime_filmes(filmes_que_quero_imprimir):
  print("A lista de filmes que eu tenho disponível")
  print(filmes)

imprime_filmes(filmes)

filmes[1]

filmes[0]

filmes[-1]

filmes[-2]

filmes[1:]

filmes[-2:]

for filme in filmes:
  print(filme)

def imprime_filmes(filmes_que_quero_imprimir):
  print("A lista de filmes que eu tenho disponível")
  for filme in filmes_que_quero_imprimir:
    print(filme)

imprime_filmes(filmes)

dados = {
    "nome" : "Joacy",
    "idade" : 25,
    "empresa" : "JMesquita"
}
dados

dados["nome"]

dados["empresa"]

dados["idade"]

