# -*- coding: utf-8 -*-
"""Aula de Data Science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MFSEoumuS-Jy65WwRTP4mFhuHwygrbsq
"""

import pandas as pd

uri = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula4.1/movies.csv"
filmes = pd.read_csv(uri) #data frame
filmes.head()

filmes.columns

filmes.columns = ["filmeId", "titulo", "generos"]
filmes.head()

uri_notas = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula1.2/ratings.csv"
notas = pd.read_csv(uri_notas) #data frame
notas.head()

notas.columns = ["usuarioId", "filmeId", "nota", "instante"]
notas.head()

notas["nota"].head() #series

notas["nota"].unique()

notas["nota"].mean()

notas["nota"].min()

notas["nota"].max()

notas.describe()

notas["nota"].median()

